site_name: Radyz
site_author: Ernesto Chavez Sanchez
jsite_description: Personal newbie blog
pages:
  - Home: index.md
  - About: about.md
theme: 
  name: material
  palette:
    primary: blue grey
google_analytics: ['UA-41184494-1', 'radyz']
extra:
  social:
    - type: 'github'
      link: 'https://github.com/radyz'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/ernesto-chavez-00857369/'
    - type: 'stack-overflow'
      link: 'https://stackoverflow.com/users/story/1200767'
  extra:
    disqus: 'radyz'
markdown_extensions:
  - meta
  - admonition
  - footnotes
  - smarty
  - toc:
      permalink: True
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      use_pygments: True
      linenums: True
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.tasklist
  - pymdownx.keys
  - pymdownx.betterem
  - pymdownx.mark
plugins:
  - search
dev_addr: '0.0.0.0:8000'
