site_name: Radyz
site_url: https://radyz.me/
site_author: Ernesto Chavez Sanchez
site_description: Tales of a newbie
nav:
  - Django: 
    - django/drf-pagenumber-paginator-performance.md
    - django/cloud-run-app.md
theme: 
  name: material
  palette:
    primary: red
google_analytics: 
  - 'UA-41184494-1'
  - 'auto'
extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/radyz'
    - icon: 'fontawesome/brands/stack-overflow'
      link: 'https://stackoverflow.com/users/story/1200767'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/in/ernesto-chavez-00857369/'
  disqus: 'radyz'
markdown_extensions:
  - meta
  - admonition
  - footnotes
  - smarty
  - toc:
      permalink: True
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      use_pygments: True
      linenums: True
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist
  - pymdownx.keys
  - pymdownx.betterem
  - pymdownx.mark
plugins:
  - search:
      lang:
        - en
extra_javascript:
  - https://unpkg.com/mermaid@8.6.4/dist/mermaid.min.js
