site_name: Radyz
site_url: https://radyz.me/
site_author: Ernesto Chavez Sanchez
site_description: Tales of a newbie
pages:
  - Home: index.md
  - Blog:
    - blog/drf-pagenumber-paginator-performance.md
theme: 
  name: material
  palette:
    primary: red
google_analytics: 
  - 'UA-41184494-1'
  - 'Radyz'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/radyz'
    - type: 'stack-overflow'
      link: 'https://stackoverflow.com/users/story/1200767'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/ernesto-chavez-00857369/'
  disqus: 'radyz'
markdown_extensions:
  - meta
  - admonition
  - footnotes
  - smarty
  - toc:
      permalink: True
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      use_pygments: True
      linenums: True
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.tasklist
  - pymdownx.keys
  - pymdownx.betterem
  - pymdownx.mark
plugins:
  - search
dev_addr: '0.0.0.0:8000'
